plugins {
    id 'java'
    id 'application'
}

group = 'com.projeto'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'de.gurkenlabs:litiengine:0.11.1'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.0'
    implementation 'com.google.code.gson:gson:2.10.1'
}

application {
    mainClass = 'Main'
}